# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1371625699);
user_pref("bidi.browser.ui", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.migration.version", 9);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.startup.homepage_override.buildID", "20130511120803");
user_pref("browser.startup.homepage_override.mstone", "45.0");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1371712098349");
user_pref("datareporting.policy.firstRunTime", "1371625698348");
user_pref("datareporting.sessions.current.activeTicks", 10);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 3695);
user_pref("datareporting.sessions.current.main", 52);
user_pref("datareporting.sessions.current.sessionRestored", 5014);
user_pref("datareporting.sessions.current.startTime", "1371625696992");
user_pref("datareporting.sessions.current.totalTime", 64);
user_pref("dom.w3c_touch_events.expose", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:45.0");
user_pref("extensions.installCache", "[{\"name\":\"winreg-app-global\",\"addons\":{\"ocplugin@webex.com\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\WebEx\\\\Productivity Tools\",\"mtime\":1345038992536,\"rdfTime\":1301447422000},\"{22C7F6C6-8D67-4534-92B5-529A0EC09405}\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\Trend Micro\\\\OfficeScan Client\\\\FirefoxExtension\",\"mtime\":1369744793962,\"rdfTime\":1344439270000},\"ocr@babylon.com\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\Babylon\\\\Babylon-Pro\\\\Plugins\\\\ocr@babylon.com\",\"mtime\":1345363316498,\"rdfTime\":1321280046000},\"adapter@babylontc.com\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\Babylon\\\\Babylon-Pro\\\\TC\\\\adapter@babylontc.com\",\"mtime\":1345363316366,\"rdfTime\":1304584698000}}},{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\Mozilla Firefox\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1371620776999,\"rdfTime\":1368303951000}}}]");
user_pref("extensions.lastAppVersion", "45.0");
user_pref("extensions.lastPlatformVersion", "45.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("gecko.buildID", "20130511120803");
user_pref("gecko.mstone", "45.0");
user_pref("gfx.direct3d.checkDX10", false);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("toolkit.startup.last_success", 1371625697);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1374217703);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
